---
- name: Instalar herramientas en Ubuntu/Debian
  apt:
    name:
      - htop
      - tmux
      - speedtest-cli
    state: present
    update_cache: yes
  when: ansible_pkg_mgr == "apt"

- name: Instalar herramientas en Fedora
  dnf:
    name:
      - htop
      - tmux
      - speedtest-cli
    state: present
  when: ansible_pkg_mgr == "dnf"