---
- name: Crear directorio /tmp/Grupo
  file:
    path: /tmp/Grupo
    state: directory
    owner: vagrant
    mode: '0755'

- name: Generar datos.txt desde template
  template:
    src: datos.txt.j2
    dest: /tmp/Grupo/datos.txt
    owner: vagrant
    mode: '0644'